[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[nixpacks]
node-version = "18"
install-command = "npm ci"

[build.args]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=4096"
OPENAI_API_KEY = "dummy-key-for-build"
